DROP TABLE IF EXISTS history;

CREATE TABLE IF NOT EXISTS prediction_history (
  id INT AUTO_INCREMENT PRIMARY KEY,

  user_id INT NULL,              -- NULL nếu chưa login
  sex INT,
  age INT,
  bmi FLOAT,
  highbp INT,
  highchol INT,
  smoker INT,
  physactivity INT,

  risk_prob FLOAT NOT NULL,      -- xác suất (0–1 hoặc %)
  risk_label VARCHAR(20),        -- Low / Medium / High

  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,

  INDEX(user_id),
  CONSTRAINT fk_history_user
    FOREIGN KEY (user_id) REFERENCES users(id)
    ON DELETE SET NULL
);
USE KiThuatDuLieu;

ALTER TABLE prediction_history
 ADD COLUMN IF NOT EXISTS cholcheck TINYINT NULL,
 ADD COLUMN IF NOT EXISTS stroke TINYINT NULL,
 ADD COLUMN IF NOT EXISTS heartdiseaseorattack TINYINT NULL,
 ADD COLUMN IF NOT EXISTS fruits TINYINT NULL,
 ADD COLUMN IF NOT EXISTS veggies TINYINT NULL,
 ADD COLUMN IF NOT EXISTSN hvyalcoholconsump TINYINT NULL,
  ADD COLUMN IF NOT EXISTS anyhealthcare TINYINT NULL,
  ADD COLUMN IF NOT EXISTS nodocbccost TINYINT NULL,
ADD COLUMN IF NOT EXISTSgenhlth TINYINT NULL,
 ADD COLUMN IF NOT EXISTS menthlth TINYINT NULL,
ADD COLUMN IF NOT EXISTSphyshlth TINYINT NULL,
 ADD COLUMN IF NOT EXISTS diffwalk TINYINT NULL,
ADD COLUMN IF NOT EXISTS education TINYINT NULL,
 ADD COLUMN IF NOT EXISTS income TINYINT NULL;
